# Generated by Django 5.1.6 on 2025-03-26 18:40

import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewpermissionrulecategory',
            options={'verbose_name': 'Ruxsat kategoriyasi', 'verbose_name_plural': 'Ruxsat kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='viewpermissionrulegroup',
            options={'verbose_name': 'Ruxsat guruhi', 'verbose_name_plural': 'Ruxsat guruhlari'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Xodim holati'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.validators.phone_validator], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'O‘qituvchi'), ('student', 'O‘quvchi')], default='student', max_length=20, verbose_name='Foydalanuvchi turi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='viewpermission',
            name='method',
            field=models.CharField(default='POST', max_length=10, verbose_name='HTTP usul'),
        ),
        migrations.AlterField(
            model_name='viewpermission',
            name='view_name',
            field=models.CharField(max_length=255, verbose_name='Ko‘rish nomi'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='users.viewpermissionrulecategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrule',
            name='permission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rule', to='users.viewpermission', verbose_name='Ko‘rish ruxsati'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrule',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ruxsat nomi'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrulecategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrulegroup',
            name='permissions',
            field=models.ManyToManyField(related_name='groups', to='users.viewpermissionrule', verbose_name='Ruxsatlar'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrulegroup',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Guruh nomi'),
        ),
    ]
