# Generated by Django 5.1.6 on 2025-03-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_viewpermissionrulecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Ro‘yxatdan o‘tgan sana'),
            preserve_default=False,
        ),
    ]
