# Generated by Django 5.1.6 on 2025-03-26 18:52

import django.db.models.deletion
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewpermissionrulecategory',
            options={'verbose_name': 'Ruxsatlar kategoriyasi', 'verbose_name_plural': 'Ruxsatlar kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='viewpermissionrulegroup',
            options={'verbose_name': 'Ruxsatlar guruhi', 'verbose_name_plural': 'Ruxsatlar guruhlari'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Xodimlarning holati'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, null=True, validators=[users.validators.phone_validator], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'O‘qituvchi'), ('student', 'O‘quvchi')], default='student', max_length=255, verbose_name='Foydalanuvchi turi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='viewpermission',
            name='method',
            field=models.CharField(default='post', max_length=255, verbose_name='Usul'),
        ),
        migrations.AlterField(
            model_name='viewpermission',
            name='view_name',
            field=models.CharField(max_length=255, verbose_name='Ko‘rish klassi'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permission_rule', to='users.viewpermissionrulecategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrule',
            name='permission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='permission_rule', to='users.viewpermission', verbose_name='Ko‘rish oynasi'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrule',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrulecategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrulegroup',
            name='permissions',
            field=models.ManyToManyField(to='users.viewpermissionrule', verbose_name='Ruxsatlar'),
        ),
        migrations.AlterField(
            model_name='viewpermissionrulegroup',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
    ]
