# Generated by Django 5.1.6 on 2025-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_useranswer_usertestsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('text_answer', 'Text Answer')], default='multiple_choice', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='testcategory',
            unique_together={('subject', 'name')},
        ),
    ]
